openapi: 3.0.3
info:
  title: Catalog Process Micro Service
  description: This service is the catalog process
  version: '{{version}}'
servers:
  - url: /pdnd-interop-uservice-catalog-process/0.0.1
    description: This service is the catalog process
security:
  - bearerAuth: [ ]
tags:
  - name: process
    description: Implements catalog process
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: health
    description: Verify service status
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /eservices:
    get:
      tags:
        - process
      summary: Get all EServices
      description: Return the list of all EServices
      operationId: listEServices
      responses:
        200:
          description: List of EServices
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EService'
  /status:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - health
      summary: Health status endpoint
      description: Return ok
      operationId: getStatus
      responses:
        '200':
          description: successful operation
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
#  /documents:
#    post:
#      tags:
#        - pet
#      summary: Add a document
#      operationId: addDocument
#      requestBody:
#        description: A document
#        content:
#          multipart/form-data:
#            schema:
#              type: object
#              required:
#                - description
#                - doc
#              properties:
#                description:
#                  type: string
#                doc:
#                  type: string
#                  format: binary
#      responses:
#        200:
#          description: successful operation
components:
  schemas:
    EService:
      required:
        - name
      type: object
      properties:
        id:
          type: string
          pattern: "^\\d+"
        name:
          type: string
          example: doggie
          maxLength: 64
          minLength: 6
    Problem:
      properties:
        detail:
          description:
            A human readable explanation specific to this occurrence of the problem.
          example: Request took too long to complete.
          maxLength: 4096
          pattern: '^.{0,1024}$'
          type: string
        status:
          description:
            The HTTP status code generated by the origin server for this occurrence
            of the problem.
          example: 503
          exclusiveMaximum: true
          format: int32
          maximum: 600
          minimum: 100
          type: integer
        title:
          description:
            A short, summary of the problem type. Written in english and readable
          example: Service Unavailable
          maxLength: 64
          pattern: '^[ -~]{0,64}$'
          type: string
      additionalProperties: false
      required:
        - status
        - title