object Versions {
  lazy val akkaHttpJson4sVersion       = "1.39.2"
  lazy val akkaHttpVersion             = "10.2.10"
  lazy val akkaManagementVersion       = "1.1.4"
  lazy val akkaVersion                 = "2.6.20"
  lazy val cassandraPersistenceVersion = "1.0.5"
  lazy val catsVersion                 = "2.8.0"
  lazy val commonsFileUploadVersion    = "1.4"
  lazy val httpJson4sVersion           = "1.37.0"
  lazy val jacksonVersion              = "2.11.4"
  lazy val jdbcPersistenceVersion      = "5.0.1"
  lazy val json4sVersion               = "4.0.6"
  lazy val logbackVersion              = "1.4.4"
  lazy val mustacheVersion             = "0.9.10"
  lazy val openapi4jVersion            = "1.0.7"
  lazy val projectionVersion           = "1.2.1"
  lazy val resilience4jVersion         = "1.7.1"
  lazy val s3Persistence               = "1.2.157"
  lazy val scalaMockVersion            = "5.2.0"
  lazy val scalapbVersion              = "0.11.1"
  lazy val scalatestVersion            = "3.2.14"
  lazy val slickVersion                = "3.3.3"
  lazy val swaggerValidatorVersion     = "2.23.0"
}

object PagopaVersions {
  lazy val agreementManagementVersion         = "1.0.x-SNAPSHOT"
  lazy val attributeRegistryManagementVersion = "1.0.x-SNAPSHOT"
  lazy val catalogManagementVersion           = "1.0.x-SNAPSHOT"
  lazy val commonsVersion                     = "1.0.x-SNAPSHOT"
  lazy val tenantManagementVersion            = "1.0.x-SNAPSHOT"
  lazy val authorizationManagementVersion     = "1.0.x-SNAPSHOT"
}
