name: CI RC Tags

on:
  push:
    tags:
      # - '*-rc[0-9]+$'
      - 'ci-refactor*'

jobs:
  retag_dev_to_uat:
    name: Retag DEV to UAT
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [2.13.10]
        java: [temurin@11]
    environment: test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Normalize repo name
        run: |
          # github.repository is in the format "owner/repository-name", we need only the repo name
          NORM_REPO="$(echo "${{ github.repository }}" | cut -d"/" -f2)"
          echo "NORM_REPO=$NORM_REPO" >> "$GITHUB_ENV"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
          role-session-name: ${{ env.NORM_REPO }}-${{ github.run_number }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'
          registries: "${{ secrets.DEV_ACCOUNT_ID }},${{ secrets.TEST_ACCOUNT_ID }}"

      - name: Retag & push from DEV to TEST
        run: |
          APP_ECR_REPO_DEV="${{ secrets.DEV_ECR_URL }}/${{ env.NORM_REPO }}"
          APP_ECR_REPO_TEST="${{ secrets.TEST_ECR_URL }}/${{ env.NORM_REPO }}"

          APP_IMAGE_COMMIT_DEV="${APP_ECR_REPO_DEV}:commit-${{ github.sha }}"
          APP_IMAGE_COMMIT_TEST="${APP_ECR_REPO_TEST}:commit-${{ github.sha }}"

          echo "Pulling from DEV..."
          docker pull "${APP_IMAGE_COMMIT_DEV}"

          echo "Retagging..."
          docker tag "${APP_IMAGE_COMMIT_DEV}" "${APP_IMAGE_COMMIT_TEST}"
          docker tag "${APP_IMAGE_COMMIT_TEST}" "${APP_ECR_REPO_TEST}:${{ github.ref_name }}"

          echo "Pushing to TEST..."
          docker push -a "${APP_ECR_REPO_TEST}"




